language: java
jdk:
- openjdk8
- oraclejdk9
notifications:
  email:
    recipients:
    - one@example.com
    on_success: always
    on_failure: never
deploy:
  provider: heroku
  api_key:
    secure: DyJngXiAOvNyvajdaZGN17Jxl+soluZ6Le6Ht4B23jaY7FPaTOf5bv2Ebkv5WmdD3dO3x0LjIElgSthkGrJ/o2QVW+JGRzR7IqRYF5qP+A3WUNIGa2Uu1xjz9JgbDJZ7F3NP/wKah1YEr9CCbnp5V7r97zUg20Cv+IofSYwTlg+xkCMzONI/HR8kFyPH7zCZtUHcAE/oW7iw0KwFdG9UPsvD6FQoULQnWvdw2sYRTMzMtzPtWfjYBNkj4/xZOYyxGAIvDlCBF0NbUwwc0rwsii5dCuLl41+HtwaWHDz1gWyyx0gf++IKTG7WnGzqxQzKpEeO5IoUBZ4+ckmGbzRj5xuHTDoN/NaecYQtqRSNYu/zgy18x2fllxhNHZFTWc7SxI1kUxFJ9f69UTIpC35R4o77kM7JQoMAKo5JZhPyf1dVUIa4HhlmObffK7Yv9GZqImco2Z+F7kWxTImAh80P26VWUZ8fhT/nv4rOZ9+W4jbdBcLh1jugGPg9KSSAP4ZyWshx7JOpz7N/mkAJ0rl0VNVI9bHEVmAuXkzsce/M5RzE1r/tecT6V6CvDa80yHxaaKPYge7G+Vg+MxRQtICGwkfdMR04n40NcBkygzhaJNNbL5oyHuoIvkJ9kMITjdi8C1SxP1Oq9JwmhCu4Ra8m4IQoYCAMGJaAWzEX5EH0wSo=
  app: prueba6
  on:
    repo: vicrosa25/hello-java
